### ISSUE TITLE
Adjuntar documento clinico en RUP

### ISSUE THREAD

**Issue by negro89** [andes/mobile-app#18]
Se ingresó a HUDS -> consulta fuera de agenda, se agregó un concepto a la consulta del paciente y se seleccionó la opcion "Desde mi app movil". **Se debería poder adjuntar un archivo desde el celular.**

Queda "ciclando" el loader:
![issue archivo clinico](https://user-images.githubusercontent.com/37875706/40368306-df1c0060-5db1-11e8-8e67-fe1beff2c391.png)

**Comment by liquid36** [comment]
Queda ciclando el loader hasta que desde el celular se adjunte una imagen o archivo.  Posiblemente falta configurar  el entorno para interactuar con la mobile.

**Comment by sychus** [comment]
No es posible reproducir el error. Está funcionando correctamente!

**Comment by liquid36** [comment]
Quedo resuelto en la última actualización.
