### ISSUE TITLE
Pantalla de ingreso

### ISSUE THREAD

**Issue by negro89** [andes/mobile-app#19]
En algunos dispositivos móviles la pantalla de ingreso no responde bien a la configuración de estilos.

![pantallazo-2018-05-22 13-13-43](https://user-images.githubusercontent.com/37875706/40375464-0bb6e134-5dc2-11e8-9af8-d1f54e743f56.png)

**Comment by liquid36** [comment]
No se ve la imagen

**Comment by negro89** [comment]
Tarda un poco en cargarse..

**Comment by sychus** [comment]
@liquid36 esto ya fue solucionado?
