### ISSUE TITLE
Error en ingreso a la aplicación 

### ISSUE THREAD

**Issue by milagrosn** [andes/mobile-app#23]
### Comportamiento actual
* Para el modelo Samsung Galaxy note 8 version 8.0 no permite el ingreso a la aplicación, se mandaron 3 mensajes de notificación desde el celular.
### Resultado esperado 
* Tener acceso a la aplicación desde cualquier modelo/versión

### Pasos para reproducir el problema 
1. Desde el modelo de celular mencionado descargar aplicacion
2. Al querer ingresar salta mensaje de error
3. 

![image](https://user-images.githubusercontent.com/39344609/44460222-996c3e80-a5e2-11e8-898c-5e3a5f31f780.png)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by sychus** [comment]
Se soluciona el problema del Splash en esta nueva versión.
