### ISSUE TITLE
Visualización de turnos reasignados

### ISSUE THREAD

**Issue by silviroa** [andes/mobile-app#25]
### Comportamiento actual
* Cuando un turno fue reasignado (por la app web) en la app mobile se muestra por debajo del turno reasignado.

### Resultado esperado 
* El badge que indica que un turno fue reasignado se vea en el turno correcto.

### Pasos para reproducir el problema 
1. Dar varios turnos por la app web para un mismo paciente
2. Visualizar en la app mobile el listado de turnos
3. Suspender un turno
4. Visualizar en la app mobile el turno suspendido
5. Reasignar el turno suspendido (por la app web)
6. Visualizar el listado de turnos en la app mobile 

![image](https://user-images.githubusercontent.com/11513044/46572480-df941c00-c95c-11e8-9906-e4bc7ba9abd5.png)

![image](https://user-images.githubusercontent.com/11513044/46572529-c770cc80-c95d-11e8-909e-d0c1e79f9e12.png)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by sychus** [comment]
solved
