### ISSUE TITLE
Turnos suspendidos

### ISSUE THREAD

**Issue by silviroa** [andes/mobile-app#26]
### Comportamiento actual
Desde la app mobile cuando un turno fue suspendido, si bien se visualiza como suspendido, te deja cancelarlo igualmente. 

### Resultado esperado 
Cuando un turno fue suspendido que no aparezca el botón para cancelar turno y que se muestre un bagde de suspendido

### Pasos para reproducir el problema 
1. Dar un turno por la app web
2. Suspender el turno
3. Ingresar a mis turnos en la app mobile
4. Ingresar al turno suspendido

![image](https://user-images.githubusercontent.com/11513044/46572636-d5bfe800-c95f-11e8-95a3-34c7275fe15d.png)

![image](https://user-images.githubusercontent.com/11513044/46572668-5383f380-c960-11e8-8536-c8d74804f6da.png)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by sychus** [comment]
Solved

**Comment by jfgabriel** [comment]
@sychus con la última versión no se resolvió

**Comment by sychus** [comment]
No entiendo.... la versión anterior tenía el bug, pero con la última que envié se resuelve. Yo ya no puedo reproducir el problema. @jfgabriel ¿podrías enviarme los pasos para poder reproducir el problema?

**Comment by silviroa** [comment]
Yo también lo veo resuelto con la ultima versión enviada.

**Comment by sychus** [comment]
layer 8 @jfgabriel
