### ISSUE TITLE
Mejoras UI

### ISSUE THREAD

**Issue by jfgabriel** [andes/mobile-app#27]
### Comportamiento actual

1. El texto debería ser **La solicitud de turnos está funcionando como prueba piloto sólo para turnos de Odontología en Neuquén Capital. En breve se irán sumando nuevas prestaciones**
![image](https://user-images.githubusercontent.com/16528734/46576037-767dca00-c997-11e8-9325-203fcc57119a.png)

2. Poner un botoncito verde para **Solicitar turno en este Centro de Salud**
![image](https://user-images.githubusercontent.com/16528734/46576033-5948fb80-c997-11e8-82c3-d26f52a9e7a4.png)

3. No poner el CS en el título de la página. Además el texto debería ser **Si Ud. no puede concurrir al turno por favor recuerde cancelarlo a través de esta aplicación móvil, o comunicándose telefónicamente al Centro de Salud, para creo que otro paciente pueda tomarlo. ¡Muchas gracias!**
![image](https://user-images.githubusercontent.com/16528734/46576048-ab8a1c80-c997-11e8-918e-d0c9d6fb6eea.png)

4. La parte de arriba del nombre del CS se cropea (aumentar alto). Además la fecha no se ve completa
![image](https://user-images.githubusercontent.com/16528734/46576054-d2485300-c997-11e8-9fea-d463d52a9e90.png)

### Resultado esperado 
* ¿Que espera que suceda?

### Pasos para reproducir el problema 
1. 
2. 
3. 

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by sychus** [comment]
Solved!
