### ISSUE TITLE
Solicitud de turnos: problema con agendas con citación por segmento

### ISSUE THREAD

**Issue by jfgabriel** [andes/mobile-app#28]
### Comportamiento actual
* En las agendas de citación por segmento debería sólo mostrarse un turno por segmento:
![image](https://user-images.githubusercontent.com/16528734/46576064-2c491880-c998-11e8-83df-e39e87653b90.png)

**Comment by sychus** [comment]
Solved

**Comment by sychus** [comment]
verificar con testing en el prox. release
