### ISSUE TITLE
Solicitar turno: problema con GPS en Android 6

### ISSUE THREAD

**Issue by jfgabriel** [andes/mobile-app#29]
### Comportamiento actual
* En un celular Moto con Android 6 se queda colgado en la ubicación
![image](https://user-images.githubusercontent.com/16528734/46576105-125c0580-c999-11e8-83be-21445a34683e.png)

![image](https://user-images.githubusercontent.com/16528734/46576101-0a03ca80-c999-11e8-88cc-4ed0366efa6d.png)

**Comment by sychus** [comment]
@jfgabriel se solucionó el problema en este dispositivo? En caso afirmativo por favor cerrar el issue. Gracias
