### ISSUE TITLE
Solicitud de turno: problema GPS con Android 8 (S8+)

### ISSUE THREAD

**Issue by jfgabriel** [andes/mobile-app#30]
### Comportamiento actual
* En un S8+ con Android 8 hay varios problemas con el GPS:
 
1. Si rechazo el permiso, me queda la pantalla colgada sin darme ninguna advertencia de que no tiene acceso al GPS.
2. Si doy permiso, la primera vez se queda colgado. Tengo que salir, y volver a entrar.

**Comment by sychus** [comment]
@jfgabriel se solucionó este issue? en caso afirmativo por favor cerrar el issue. Gracias
