### ISSUE TITLE
Historial de turnos - turnos asignados desde la app mobile

### ISSUE THREAD

**Issue by milagrosn** [andes/mobile-app#31]
### Comportamiento actual
* Cuando un paciente tiene turno generado desde la app mobile, luego no se le pueda generar turno desde la app para otra prestación
### Resultado esperado 
* Permitir dar otros turnos desde la app a paciente q tiene algun turno generado desde la app mobile

### Pasos para reproducir el problema 
1. Paciente saca turno desde la app mobile
2. Buscar el paciente y seleccionarlo
3. Desde la app intentar darle turno en otro efector

![image](https://user-images.githubusercontent.com/39344609/46624452-2de51e80-cb07-11e8-8b67-c19fd0c44a3c.png)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by sychus** [comment]
Solved desde la api
