### ISSUE TITLE
Suspencion de turnos por la APP

### ISSUE THREAD

**Issue by milagrosn** [andes/mobile-app#32]
### Comportamiento actual
* Cuando se suspende un turno desde la APP, el paciente desde su APP MOBILE no puede volver a sacar turno. 
### Resultado esperado 
* En caso que desde la APP se le suspenda un turno al paciente, el paciente tenga la posibilidad de poder generarse otro turno.

### Pasos para reproducir el problema 
1. Paciente saca turno desde la app mobile
2. Desde la app se le suspende el turno
3. Intentar que el paciente vuelva a generar un turno desde la app mobile

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by sychus** [comment]
Esto no es correcto. Según el workflow, si el turno es suspendido por gestión de pacientes debe reasignarlo debido a que es algo ajeno al paciente. Si el turno no va a ser reasignado debe ser liberado, así no queda bloqueado el turno.

**Comment by sychus** [comment]
@milagrosn , @condorpiedra y @kroce en caso que yo esté equivocado por favor especificar el workflow y re abrir el issue. Gracias
