### ISSUE TITLE
Dación de múltiples Turnos por la app

### ISSUE THREAD

**Issue by condorpiedra** [andes/mobile-app#33]
### Comportamiento actual
* El paciente puede solicitar y asignarse varios turnos por la app mobile

### Resultado esperado 
* El paciente debería poder solicitar un único turno

### Pasos para reproducir el problema 
1. Loguearse como paciente en la app mobile
2. Presionar "Mis Turnos"
3. Antes que cargue el historial de pacientes presionar "Solicitar Turno"
4. Seleccionar un turno disponible
5 Repetir varias veces 3, 4 y 5

**Comment by sychus** [comment]
Solved! El problema era con conexiones lentas el botón quedaba disponible hasta que volvía de la promise.
