### ISSUE TITLE
Visualización de agendas suspendidas

### ISSUE THREAD

**Issue by condorpiedra** [andes/mobile-app#34]
### Comportamiento actual
* Se ingresa a un efector para visualizar los turnos disponibles.  La app muestra turnos correspondientes a agendas suspendidas.  Cuando se selecciona algún turno, la app emite un error y no permite asignarlo.  

### Resultado esperado 
* Después de presionar el botón confirmar verificar nuevamente el estado de las agendas para no mostrar aquellas agendas que fueron suspendidas mientras el paciente seleccionaba un turno disponible.

### Pasos para reproducir el problema 
1. Loguearse como paciente.
2. Ingresar a un efector.
3. Seleccionar un turno disponible.
4. Por la app de andes ingresar al gestor de agendas y suspender la agenda.
5. Presionar el botón "Cofirmar" en la app mobile.
6. Aparece un "Error" en la asignación 
7. Volver a los turnos disponibles.
8. Visualizar los turnos de agendas suspendidas.
(Tener en cuenta que una vez que el paciente se desloguea y vuelve a iniciar sesión los turnos asociados a estas agendas no se visualizan)

**Comment by sychus** [comment]
@condorpiedra lo pude solicionar desde la app de una forma bastante sencilla.... habría que probar y si esta ok. Cerrar el issue

**Comment by sychus** [comment]
ya esta solucionado, manda una notificación que ese turno ya no está disponible y muestra que no hay turnos disponibles.
