### ISSUE TITLE
Agendas sin profesional

### ISSUE THREAD

**Issue by condorpiedra** [andes/mobile-app#35]
### Comportamiento actual
* Se selecciona un turno de correspondiente a una agenda sin profesional.  El turno puede asignarse de forma correcta pero al ingresar a "Mis Turnos" para liberarlo, la app no responde. Se debe presionar el botón atrás.  para lograr visualizar el turno.

### Resultado esperado 
* Poder visualizar el turno sin necesidad de presionar los botones atrás.

### Pasos para reproducir el problema 
1. Loguearse como paciente
2. Buscar un turno disponible correspondiente a una agenda sin profesional
3. Seleccionar un turno y presionar Confirmar.
4. Ingresar a "Mis Turnos", visualizar el turno asignado.  
5. Presionar sobre el turno para cancelarlo
6. La app no responde al evento.  Presionar atrás para poder visualizarlo.

**Comment by sychus** [comment]
Solved!
