### ISSUE TITLE
Agendas con más de un bloque

### ISSUE THREAD

**Issue by condorpiedra** [andes/mobile-app#36]
### Comportamiento actual
* En agendas con más de un bloque de turnos programados se visualizan los turnos disponibles sólo del primero bloque.

### Resultado esperado 
* Visualizar los turnos programados de todos los bloques de una agenda.

### Pasos para reproducir el problema 
1. Crear un agenda con más de un bloque con turnos programados en el gestor de agendas en la app
2. Loguearse como paciente
3. Ingresar al Efector donde se creó la agenda. 
4. Visualizar los turnos disponibles sólo del primer bloque

**Comment by sychus** [comment]
Solved en la nueva versión de la app mobile que mostraremos en la demo del lunes 18/02/2019
