### ISSUE TITLE
Solicitar turno

### ISSUE THREAD

**Issue by milagrosn** [andes/mobile-app#40]
### Comportamiento actual
* El botón solicitar turno no trae las agendas disponibles en los efectores. (no responde)

### Resultado esperado 
* Que me muestre las agendas disponibles para la solicitud de turno

### Pasos para reproducir el problema 
1. Crear agenda con turnos disponibles para la app mobile
2. Intentar solicitar turno...
3.

![image](https://user-images.githubusercontent.com/39344609/53960556-57f63900-40c5-11e9-985e-0cc1ee2df744.png)

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by sychus** [comment]
Se soluciono habilitando le flag en la base de datos para que las organizaciones acepten turnos mobile en true.
