### ISSUE TITLE
Agendas con más de una prestación

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/mobile-app#58]
### Comportamiento actual
*MEJORA*
Al momento de configurar turnos por app mobile en una agenda con más de un prestación, no es posible indicar para que prestación, por lo que en la app se muestran ambas prestaciones.

### Resultado esperado 
Se sugiere poder indicar para que prestación/es se quiere configurar turnos por app, cuando se trata de una agenda con un bloque y dos o mas prestaciones. Por ejemplo Medicina general y niño sano

### Pasos para reproducir el problema 
1. 
2. 
3. 

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by sychus** [comment]
@Silvinagabriela entiendo que esta funcionalidad es una mejora para agregar a CITAS. Ya que no hay nada que hacer desde la app mobile para resolver este tema. ¿podrías generar el issue en app?
