### ISSUE TITLE
Mensaje de información para el usuario cuando se libera un turno

### ISSUE THREAD

**Issue by Silvinagabriela** [andes/mobile-app#60]
### Comportamiento actual
Cuando un turno es liberado por gestión de pacientes, la app no muestra ningún tipo de información al paciente. 

### Resultado esperado 
Avisar al paciente que su turno fue liberado con opción a tomar otro turno.. 

### Pasos para reproducir el problema 
1. 
2. 
3. 

<!-- Código relevante 

  ```
  // TODO: Código que considere importante incorporar.  
  ``` -->

**Comment by sychus** [comment]
@Silvinagabriela ya estaba el issue
