### ISSUE TITLE
No se visualizan correctamente las farmacias de turno

### ISSUE THREAD

**Issue by kroce** [andes/mobile-app#75]
### Comportamiento actual
* Al ingresar a ver las farmacias de turno se pierden algunas localidades en el select

### Resultado esperado 
* Que se pueda seleccionar correctamente la localidad del select

### Pasos para reproducir el problema 
1. Ingresar a la app mobile
2. Acceder al icono de farmacias de turno
3. las localidades no se visualizan correctamente

![bugFarmacias](https://user-images.githubusercontent.com/18030170/69983230-f1e3f880-1514-11ea-850b-17064f6df85f.jpeg)

**Comment by palita1991** [comment]
Se cierra, resuelto en PR https://github.com/andes/mobile-app/pull/78
